apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  labels:
    app: classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classifier
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
      - name: classifier
        image: solsoria/classifier:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: classifier-configmap
        - secretRef:
            name: classifier-secret
        